# Generated by Django 4.0 on 2021-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePrenda', models.CharField(max_length=50)),
                ('Categoría', models.CharField(max_length=200)),
                ('Imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
