# Generated by Django 4.0 on 2021-03-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=50)),
                ('NombrePrenda', models.CharField(max_length=50)),
                ('Categoría', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
    ]
