# Generated by Django 4.0 on 2021-03-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210324_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=50)),
                ('NombrePrenda', models.CharField(max_length=50)),
                ('Categoría', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Imagen', models.ImageField(upload_to='examen/media/prenda')),
            ],
        ),
        migrations.DeleteModel(
            name='Articulo1',
        ),
    ]
